export enum Rank {
  Ace = "ACE",
  Two = "TWO",
  Three = "THREE",
  Four = "FOUR",
  Five = "FIVE",
  Six = "SIX",
  Seven = "SEVEN",
  Eight = "EIGHT",
  Nine = "NINE",
  Ten = "TEN",
  Jack = "JACK",
  Queen = "QUEEN",
  King = "KING",
}
